baseURL = "https://shapeshed.com/"
languageCode = "en-gb"
theme = "tufte-catppuccin"
title = "George Ornbo"
copyright = "Shape Shed"
metaDataFormat = "json"
rssLimit = "20"
sitemap = "sitemap.xml"
googleAnalytics= "G-ZF9SLMN89W"
enableGitInfo = true

[permalinks]
  posts = "/:slug/"
[params]
  author = "George Ornbo"
  description = "Articles by George Ornbo, a UK-based technologist"
  firstName = "George"
  lastName = "Ornbo"
  gender = "male"
  username = "shapeshed"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

[markup]
  [markup.highlight]
    style = 'catppuccin-mocha'
    noclasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
      unsafe = true

[menu]
    [[menu.nav]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

    [[menu.nav]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 2

    [[menu.nav]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

    [[menu.nav]]
    identifier = "rss"
    name = "RSS Feed"
    url = "/index.xml"
    weight = 4



[related]
    includeNewer = false
    threshold = 50
    toLower = true
[[related.indices]]
    name = 'tags'
    weight = 100
    toLower = true
[[related.indices]]
    name = 'date'
    weight = 10
[[related.indices]]
    name        = "fragmentrefs"
    type        = "fragments"
    applyFilter = false
    weight = 50

[deployment]
  [[deployment.targets]]
    name = "aws-s3"
    URL = "s3://static.shapeshed.com"
    # cloudFrontDistributionID = "EOEO7HZP7EIIC"

  [[deployment.matchers]]
    pattern = "^sitemap\\.xml$"
    cacheControl = "public, s-maxage=604800, max-age=86400" #7d,1d
    contentType = "application/xml"

  [[deployment.matchers]]
    pattern = "^.+\\.(css|js)$"
    cacheControl = "public, immutable, max-age=31536000" #1y

  [[deployment.matchers]]
    pattern = "(?i)^.+\\.(jpg|jpeg|gif|png|webp|avif|mp4|woff|woff2)$"
    cacheControl = "public, s-maxage=7776000, max-age=604800" #90d,7d

  [[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json|txt)$"
    cacheControl = "public, s-maxage=604800, max-age=3600" #7d,1h

[[resources]]
    name = 'css'
    src = 'css/style.css'

